<?php
$townnames = array ("Mayene","Tear","Illian","Ebou Dar","Tanchico","Cantorin","Falme","Bandar Eban","Maradon","Chachin","Shol Arbela","Fal Dara","Thakan'dar","Rhuidean","Stedding Shangtai","Far Madding","Caemlyn","Cairhien","Tar Valon","Lugard","Emond's Field","Salidar","Jehannah","Amador");

$map_data = array(
"Mayene" => array("Bay of Remara","Aiel Waste","Plains of Maredo","Garen's Wall"),
"Tear" => array("Sea of Storms","Bay of Remara","Haddon Mirk","Shadow Coast"),
"Illian" => array("Plains of Maredo","Sea of Storms","Kinslayer's Dagger","Windbiter's Finger"),
"Ebou Dar" => array("Shadow Coast","Windbiter's Finger","Sea of Storms","Caralain Grass"),
"Tanchico" => array("Aryth Ocean","Garen's Wall","Windbiter's Finger","Paerish Swar"),
"Cantorin" => array("Windbiter's Finger","Shadow Coast","Aryth Ocean","Bay of Remara"),
"Falme" => array("Almoth Plain","Aryth Ocean","Garen's Wall","Sea of Storms"),
"Bandar Eban" => array("Paerish Swar","World's End","Almoth Plain","Aryth Ocean"),
"Maradon" => array("World's End","Plain of Lances","Paerish Swar","Mountains of Mist"),
"Chachin" => array("Plain of Lances","Black Hills","Braem Wood","World's End"),
"Shol Arbela" => array("Field of Merrilor","Kinslayer's Dagger","Plain of Lances","Spine of the World"),
"Fal Dara" => array("Tarwin's Gap","Blasted Lands","Spine of the World","Field of Merrilor"),
"Thakan'dar" => array("Blasted Lands","Tarwin's Gap","Aiel Waste","Kinslayer's Dagger"),
"Rhuidean" => array("Aiel Waste","Spine of the World","Tarwin's Gap","Braem Wood"),
"Stedding Shangtai" => array("Spine of the World","Haddon Mirk","Bay of Remara","Aiel Waste"),
"Far Madding" => array("Haddon Mirk","Hills of Kintara","Field of Merrilor","Plains of Maredo"),
"Caemlyn" => array("Braem Wood","Caralain Grass","Hills of Kintara","Blasted Lands"),
"Cairhien" => array("Kinslayer's Dagger","Braem Wood","Blasted Lands","Haddon Mirk"),
"Tar Valon" => array("Black Hills","Field of Merrilor","World's End","Tarwin's Gap"),
"Lugard" => array("Hills of Kintara","Plains of Maredo","Mountains of Mist","Plain of Lances"),
"Emond's Field" => array("Mountains of Mist","Paerish Swar","Forest of Shadows","Almoth Plain"),
"Salidar" => array("Caralain Grass","Forest of Shadows","Black Hills","Hills of Kintara"),
"Jehannah" => array("Garen's Wall","Mountains of Mist","Caralain Grass","Forest of Shadows"),
"Amador" => array("Forest of Shadows","Almoth Plain","Shadow Coast","Black Hills"),
"Paerish Swar" => array("Bandar Eban","Emond's Field","Maradon","Tanchico"),
"Haddon Mirk" => array("Far Madding","Stedding Shangtai","Tear","Cairhien"),
"Braem Wood" => array("Caemlyn","Cairhien","Chachin","Rhuidean"),
"Forest of Shadows" => array("Amador","Salidar","Emond's Field","Jehannah"),
"Garen's Wall" => array("Jehannah","Tanchico","Falme","Mayene"),
"Hills of Kintara" => array("Lugard","Far Madding","Caemlyn","Salidar"),
"Black Hills" => array("Tar Valon","Chachin","Salidar","Amador"),
"Caralain Grass" => array("Salidar","Caemlyn","Jehannah","Ebou Dar"),
"Blasted Lands" => array("Thakan'dar","Fal Dara","Cairhien","Caemlyn"),
"Mountains of Mist" => array("Emond's Field","Jehannah","Lugard","Maradon"),
"Kinslayer's Dagger" => array("Cairhien","Shol Arbela","Illian","Thakan'dar"),
"Spine of the World" => array("Stedding Shangtai","Rhuidean","Fal Dara","Shol Arbela"),
"Aryth Ocean" => array("Tanchico","Falme","Cantorin","Bandar Eban"),
"Sea of Storms" => array("Tear","Illian","Ebou Dar","Falme"),
"Windbiter's Finger" => array("Cantorin","Ebou Dar","Tanchico","Illian"),
"Bay of Remara" => array("Mayene","Tear","Stedding Shangtai","Cantorin"),
"Almoth Plain" => array("Falme","Amador","Bandar Eban","Emond's Field"),
"Field of Merrilor" => array("Shol Arbela","Tar Valon","Far Madding","Fal Dara"),
"Plains of Maredo" => array("Illian","Lugard","Mayene","Far Madding"),
"Plain of Lances" => array("Chachin","Maradon","Shol Arbela","Lugard"),
"World's End" => array("Maradon","Bandar Eban","Tar Valon","Chachin"),
"Aiel Waste" => array("Rhuidean","Mayene","Thakan'dar","Stedding Shangtai"),
"Tarwin's Gap" => array("Fal Dara","Thakan'dar","Rhuidean","Tar Valon"),
"Shadow Coast" => array("Ebou Dar","Cantorin","Amador","Tear"),
);



?>